server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:mysql://mysql:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: sofijaaneed@gmail.com
    password: wwivnvrffchnjwlf
    properties:
      mail:
        brand: "MojaBanka"
        otp:
          subject: "kod"
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
security:
  jwt:
    issuer: http://auth-service:8081
    key:
      id: key-2025-08
      private-pem-path: /run/secrets/jwt/private_pkcs8.pem
      public-pem-path:  /run/secrets/jwt/public.pem
jwt:
#  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-ms: 900000
  refresh-token-ms: 604800000
  refresh-cookie-name: refresh_token
  refresh-cookie-path: "/"
  refresh-cookie-secure: false
  refresh-pepper: "4c7b2a0fb8bfe3a9d88f1d2b77e4c9ab0fd3b6c98c2f447fbadd7a00a1bb9e34"
s2s:
  token: some-ultra-secret-dev-token

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8761/eureka
    register-with-eureka: true
    fetch-registry: true

