server:
  port: 8085

spring:
  application:
    name: transaction-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:mysql://mysql:3306/transactiondb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8761/eureka
    register-with-eureka: true
    fetch-registry: true