server:
  port: 8084

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: loan-service
          uri: http://loan-service:8086
          predicates:
            - Path=/loans/**
        - id: account-service
          uri: http://account-service:8083
          predicates:
            - Path=/accounts/**
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid
        - id: transaction-service
          uri: http://transaction-service:8085
          predicates:
            - Path=/transactions/**
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8761/eureka/
    register-with-eureka: true
    fetch-registry: true