server:
  port: 8086

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://mysql:3306/loandb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json
    user:
      name: admin
      password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8761/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.springframework.security: DEBUG
app:
  correlation:
    header: X-Correlation-ID
management:
  endpoints:
    web:
      exposure:
        include: health,info